quarkus:
  langchain4j:
    timeout: 1m
    openai:
      api-key: "${OPENAI_KEY}"
      chat-model:
        model-name: gpt-4.1
#    mcp:
#      filesystem:
#        transport-type: stdio
#        command: "npx,-y,@modelcontextprotocol/server-filesystem,${app.output-dir}"
#      word-document-server:
#        transport-type: stdio
#        command: /opt/homebrew/bin/uvx,--from,office-word-mcp-server,word_mcp_server
#        command: npm,-y,exec,@modelcontextprotocol/server-filesystem@0.6.2,playground
#        command: /opt/homebrew/bin/python3,mcp/docx_mcp.py
#        url: http://localhost:8765
#        command: /Users/edeandre/Desktop/temp/Office-Word-MCP-Server/.venv/bin/python,/Users/edeandre/Desktop/temp/Office-Word-MCP-Server/word_mcp_server.py
#        command: /opt/homebrew/bin/uvx,mcp-server-office
#        command: npx,-y,@smithery/cli,install,@famano/mcp-server-office,--client,claude
#        command: /opt/homebrew/bin/uvx,mcp-server-office
  hibernate-orm:
    database:
      generation: drop-and-create
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

"%dev":
  quarkus:
    log:
      category:
        "org.salemhist":
          level: DEBUG
        "dev.langchain4j.mcp":
          level: DEBUG
    langchain4j:
      log-requests: true
      log-responses: true
#      openai:
#        base-url: http://localhost:11434/v1
#        chat-model:
#          model-name: llama3.2-vision:11b
    hibernate-orm:
      log:
        sql: true
